### ISSUE TITLE
3090 error during training in w Cuda 11.6

### ISSUE THREAD

**Issue by vade** [nerfstudio-project/nerfstudio#1012]
**Describe the bug**
Hi

I am trying to run through the install and setup. I was able to install `nerfstudio` on my 3x 3090 box with driver `510.85.02` and coda `11.6` (and have functioning PyTorch installed in other conda envs).

Im unable to run 

`ns-train nerfacto --data data/nerfstudio/poster` :

> NVIDIA GeForce RTX 3090 with CUDA capability sm_86 is not compatible with the current PyTorch installation.
The current PyTorch install supports CUDA capabilities sm_37 sm_50 sm_60 sm_70.
If you want to use the NVIDIA GeForce RTX 3090 GPU with PyTorch, please check the instructions at https://pytorch.org/get-started/locally/

If I update to the latest released pytorch via git, I then get:

> NameError: name 'tcnn' is not defined

What is the expected manner to install with an upgraded coda runtime / torch?

Ive tried editing the `nerfstudio.egg_info/requirements.txt` but must be missing some dependency layer and it keeps reseting torch to `1.12.1`

Thanks for any guidance.

**Comment by minsoo5403** [comment]
I solved it as follows.

pip install torch==1.12.1+cu116 torchvision==0.13.1+cu116 -f https://download.pytorch.org/whl/torch_stable.html
pip install git+https://github.com/NVlabs/tiny-cuda-nn/#subdirectory=bindings/torch
