### ISSUE TITLE
tinny-cuda wont install. CUDA not found

### ISSUE THREAD

**Issue by Sinicyn78** [nerfstudio-project/nerfstudio#1206]
(nerfstudio) root@home:/home/sinicyn/Downloads# pip install git+https://github.com/NVlabs/tiny-cuda-nn/#subdirectory=bindings/torch
Collecting git+https://github.com/NVlabs/tiny-cuda-nn/#subdirectory=bindings/torch
  Cloning https://github.com/NVlabs/tiny-cuda-nn/ to /tmp/pip-req-build-b8w1_isc
  Running command git clone --filter=blob:none --quiet https://github.com/NVlabs/tiny-cuda-nn/ /tmp/pip-req-build-b8w1_isc
  Resolved https://github.com/NVlabs/tiny-cuda-nn/ to commit 14053e9a87ebf449d32bda335c0363dd4f5667a4
  Running command git submodule update --init --recursive -q
  Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error
  
  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [10 lines of output]
      /root/anaconda3/envs/nerfstudio/lib/python3.8/site-packages/torch/cuda/__init__.py:83: UserWarning: CUDA initialization: Unexpected error from cudaGetDeviceCount(). Did you run some cuda functions before calling NumCudaDevices() that might have already set an error? Error 803: system has unsupported display driver / cuda driver combination (Triggered internally at  ../c10/cuda/CUDAFunctions.cpp:109.)
        return torch._C._cuda_getDeviceCount() > 0
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "/tmp/pip-req-build-b8w1_isc/bindings/torch/setup.py", line 30, in <module>
          raise EnvironmentError("Unknown compute capability. Specify the target compute capabilities in the TCNN_CUDA_ARCHITECTURES environment variable or install PyTorch with the CUDA backend to detect it automatically.")
      OSError: Unknown compute capability. Specify the target compute capabilities in the TCNN_CUDA_ARCHITECTURES environment variable or install PyTorch with the CUDA backend to detect it automatically.
      No CUDA runtime is found, using CUDA_HOME='/usr'
      Building PyTorch extension for tiny-cuda-nn version 1.7
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.

**Comment by THE-COB** [comment]
Where did you install CUDA_HOME and CUDA_PATH?

**Comment by Sinicyn78** [comment]
I'm trying to install in windows via conda
Installed CUDA 11.3
now these errors

<img width="1253" alt="image" src="https://user-images.githubusercontent.com/93261532/211033575-7a9b3d24-5245-438e-8497-2bf021d250c9.png">

**Comment by THE-COB** [comment]
> I'm trying to install in windows via conda
> Installed CUDA 11.3
> now these errors
> 
> <img width="1253" alt="image" src="https://user-images.githubusercontent.com/93261532/211033575-7a9b3d24-5245-438e-8497-2bf021d250c9.png">
> 

Can I see a screenshot of your system and user environment variables

**Comment by Sinicyn78** [comment]
<img width="411" alt="image" src="https://user-images.githubusercontent.com/93261532/211090254-14d8f8f5-862c-44bb-a05a-affae3b11650.png">
<img width="599" alt="image" src="https://user-images.githubusercontent.com/93261532/211090318-ec093966-7334-404d-91e8-cb1f4e788b8c.png">
<img width="603" alt="image" src="https://user-images.githubusercontent.com/93261532/211090362-49ce090d-7413-4570-829d-117b5c5b72af.png">
<img width="282" alt="image" src="https://user-images.githubusercontent.com/93261532/211090403-73ffefde-6f57-4cf6-8ad4-1b44d239c9b2.png">

**Comment by Sinicyn78** [comment]
> > I'm trying to install in windows via conda
> > Installed CUDA 11.3
> > now these errors
> > <img alt="image" width="1253" src="https://user-images.githubusercontent.com/93261532/211033575-7a9b3d24-5245-438e-8497-2bf021d250c9.png">
> 
> Can I see a screenshot of your system and user environment variables

<img width="399" alt="image" src="https://user-images.githubusercontent.com/93261532/211165251-6acd8294-8df4-4c27-854b-8dca93da4dc7.png">
<img width="704" alt="image" src="https://user-images.githubusercontent.com/93261532/211165277-508b5304-7a38-4e38-9b60-13183f3b3d79.png">
<img width="707" alt="image" src="https://user-images.githubusercontent.com/93261532/211165285-649fbbaf-3b0d-470e-b009-b3e33d52b4fe.png">
<img width="630" alt="image" src="https://user-images.githubusercontent.com/93261532/211165301-621e4aa8-93a8-4e77-866b-e12e166a55d9.png">

**Comment by THE-COB** [comment]
Try making a CUDA_HOME env variable with the same value as CUDA_PATH in both system and user variables (this way you can do it on both admin and user accounts)

**Comment by Sinicyn78** [comment]
> Try making a CUDA_HOME env variable with the same value as CUDA_PATH in both system and user variables (this way you can do it on both admin and user accounts)

now these errors:
<img width="847" alt="image" src="https://user-images.githubusercontent.com/93261532/211191033-f82495a0-82d1-4e41-b538-38e23042262d.png">
<img width="848" alt="image" src="https://user-images.githubusercontent.com/93261532/211191050-9dad428e-a052-4e02-a561-3ffcc3368c97.png">
<img width="858" alt="image" src="https://user-images.githubusercontent.com/93261532/211191070-3a45c85f-9020-49fe-a91b-bf71aad0354a.png">

**Comment by THE-COB** [comment]
Try installing ninja like in this issue [https://github.com/NVlabs/tiny-cuda-nn/issues/169#issuecomment-1291990467](https://github.com/NVlabs/tiny-cuda-nn/issues/169#issuecomment-1291990467)

**Comment by dooonnis** [comment]
I also ran into this problem and tried many solutions. I found the solution here #1177 and installed tiny-cuda-nn thanks to [this comment](https://github.com/nerfstudio-project/nerfstudio/issues/1177#issuecomment-1370521128).

To document what I have done to get nerfstudio via conda to work properly:

1. Installed CUDA 11.7 and VS 2019 and deinstalled all other versions

2. Created a conda envoriment
`conda create --name nerfstudio -y python=3.8`
`conda activate nerfstudio`
`python -m pip install --upgrade pip`

3. Installed pytorch
`pip install torch==1.12.1+cu113 torchvision==0.13.1+cu113 -f https://download.pytorch.org/whl/torch_stable.html`

4. Git cloned tiny-cuda-nn via the repo into _miniconda3\envs\nerfstudio\Lib\site-packages_
`git clone --recursive https://github.com/nvlabs/tiny-cuda-nn`
`cd tiny-cuda-nn`
`cmake . -B build`
`cmake --build build --config RelWithDebInfo -j`
(cmake commands run in VS developer command prompt)

5. Installed nerfstudio
`pip install nerfstudio`

6. Reinstalled tiny-cuda-nn via pip
`pip install git+https://github.com/NVlabs/tiny-cuda-nn/#subdirectory=bindings/torch`

How tiny-cuda-nn was installed may not makes sense, but that's what worked in the end. Nerfstudio is now fully functional.

**Comment by tancik** [comment]
Closing, feel free to reopen if it is still and issue.

**Comment by Xerthor** [comment]
> 

This one worked for me but I had to install CUDA 12.1.1 before runing cmake . -B build

**Comment by PeaceNeil** [comment]
solved this by 
`export TCNN_CUDA_ARCHITECTURES=86` 
as the error says "Unknown compute capability. Specify the target compute capabilities in the TCNN_CUDA_ARCHITECTURES environment variable or install PyTorch with the CUDA backend to detect it automatically"

mine's a 3090 Ti GPU

**Comment by lightningthief873** [comment]
> solved this by `export TCNN_CUDA_ARCHITECTURES=86` as the error says "Unknown compute capability. Specify the target compute capabilities in the TCNN_CUDA_ARCHITECTURES environment variable or install PyTorch with the CUDA backend to detect it automatically"
> 
> mine's a 3090 Ti GPU

This works very well. Check your GPU version first. Also with that the GCC version because most likely you will need to downgrade to <11. So check it well
