### ISSUE TITLE
Latest docker images dont run instant-ngp on 3080 series cards. - CUDA error: no kernel image is available for execution on the  device

### ISSUE THREAD

**Issue by kurtjcu** [nerfstudio-project/nerfstudio#2878]
**Describe the bug**
Current docker images with tags "main", "1.0.1", and "1.0.0" crash when training.

 RuntimeError: CUDA error: no kernel image is available for execution on the 
device

**To Reproduce**
Do this on a machine with a 3080 (ubuntu server, nvidia driver support up to cuda 12.3)
```bash
wandb docker-run \
            --gpus "device=1" \
            -u $(id -u) \
            -v "datadir:/workspace" \
            -v '/home/user/.cache/:/home/user/.cache/' \
            -p 7017:7007 \
            --rm -it --shm-size=12gb \
            dromni/nerfstudio:1.0.1 ns-train instant-ngp \
            --vis wandb \
            --data "/workspace" 
```

**Expected behavior**
Using the above command with container tag "0.3.4" functions correctly

**Comment by yuefengyf** [comment]
+1, similar issue also seen in `splatfacto` with docker image "1.0.0"

**Comment by rowellz** [comment]
I am getting similar issues as well for both 1.0.0 and 1.0.1 images :(

**Comment by jkulhanek** [comment]
Hi, can you please try the `nerfstudio/nerfstudio:latest` image?

**Comment by rowellz** [comment]
That seems to do the trick for me, TYSM! I've been using `gaussian-splatting` for  the `dromni/nerfstudio:main` image for a while now. Is there any difference or improvement with the `splatfacto` method in the `nerfstudio/nerfstudio:latest` image?

**Comment by jkulhanek** [comment]
Good to hear it works. I am still testing the image, so please let me know if you find any issues. Unfortunately, I don't have access to the Dockerfile used to compile dromni/nerfstudio:main, but the nerfstudio/nerfstudio:latest image just contains the current last commit in the main branch of nerfstudio.

**Comment by kurtjcu** [comment]
I was having the same issue on all the latest images as well. I used docker to compile one from main branch and then it worked.

**Comment by eduardohenriquearnold** [comment]
I was having the same issue on an NVIDIA T4, but the `nerfstudio/nerfstudio:latest` image seems to work like a charm - thanks @jkulhanek .

May I ask what have you changed? Looking online it seems to be something related to the CUDA supported architectures, but it seems like the official nerfstudio docker image contains [most common archs](https://github.com/nerfstudio-project/nerfstudio/blob/main/Dockerfile#L22), including `sm_75` which corresponds to the T4. So I'm just curious what specifically is addressing the issue here?

**Comment by jinwookpark** [comment]
I solved it to fix CUDA_ARCHITECTURES in Dockerfile and build a docker. (My gpu is NVIDIA RTX 3090)

#ARG CUDA_ARCHITECTURES=90;89;86;80;75;70;61;52;37
ARG CUDA_ARCHITECTURES=90;89;86;80;75;70

**Comment by jkulhanek** [comment]
> I was having the same issue on an NVIDIA T4, but the `nerfstudio/nerfstudio:latest` image seems to work like a charm - thanks @jkulhanek .
> 
> May I ask what have you changed? Looking online it seems to be something related to the CUDA supported architectures, but it seems like the official nerfstudio docker image contains [most common archs](https://github.com/nerfstudio-project/nerfstudio/blob/main/Dockerfile#L22), including `sm_75` which corresponds to the T4. So I'm just curious what specifically is addressing the issue here?

Sorry, but I don’t have access to dockerfiles used by dromni to build dromni/nerfstudio images. I don’t know which cuda archs they built with.

**Comment by jkulhanek** [comment]
> I solved it by modifying CUDA_ARCHITECTURES in Dockerfile and then building docker. (My GPU is NVIDIA RTX 3090)
> 
> #ARG CUDA_ARCHITECTURES=90;89;86;80;75;70;61;52;37 ARG CUDA_ARCHITECTURES=90;89;86;80;75;70

I believe 3090 has cuda compute 75, so the default docker image should work just fine. Are you having issues?
