### ISSUE TITLE
CUDA error: an illegal memory access was encountered

### ISSUE THREAD

**Issue by gchhablani** [nerfstudio-project/nerfstudio#2903]
**Describe the bug**
I am trying to run `splatfacto` on a custom dataset.
After 40 iterations, the `ns-train` command runs into the following error:
```
  File "./nerfstudio/nerfstudio/engine/callbacks.py", line 105, in run_callback
    self.func(*self.args, **self.kwargs, step=step)
  File "./nerfstudio/nerfstudio/models/splatfacto.py", line 352, in after_train
    self.vis_counts[visible_mask] = self.vis_counts[visible_mask] + 1
```

**To Reproduce**
The behavior is not exactly reproducible unless I share the data here, which I am not sure if I have the liberty to.
The training command is:
```
ns-train splatfacto \
--experiment-name=${EXP_NAME} \
--output-dir ${OUT_DIR} \
--steps-per-save=1000 \
--max-num-iterations=300000 \
--vis "${vis}" \
--timestamp "$timestamp" \
--logging.relative-log-dir="logs" \
--data=${DATA_PATH} \
blender-data
```
I modified the code as in #2902 to load a pointcloud with a blender data.

**Expected behavior**
The training happens without any issues.

**Screenshots**

I tried printing visible mask:
```
            visible_mask = (self.radii > 0).flatten()
            print("Visible Mask: ", visible_mask, " Type: ", type(visible_mask))
```
However, just before failure it doesn't print other things, only the text, so not sure what is up there:
<img width="655" alt="image" src="https://github.com/nerfstudio-project/nerfstudio/assets/29076344/b3d2f614-c36c-43f8-ba5d-13e9bc7fe04a">

**Comment by maturk** [comment]
What dataset are you using and how do the initial sfm/camera poses look like in the viewer? This "error" happens when you are splatting and there are no valid gaussians in view, so the CUDA backend most likely fails mysteriously and self.radii is either empty or never filled. From my experience, this is usually solved by verifying that my initial sfm points are in the correct coordinate frame and that I have processed my poses correctly. Just some thoughts...

**Comment by gchhablani** [comment]
Hi @maturk 
Thanks for checking this!
I am using a synthetic room dataset, with pointclouds which have holes in them and are imperfect.
I am sure the poses are right, because it works for a similar dataset, derived from the same source.

```  File "./nerfstudio/nerfstudio/models/splatfacto.py", line 344, in after_train
    print("Visible Mask: ", visible_mask, " Type: ", type(visible_mask))
  File "/User/gunjanchhablani/miniforge3/envs/nerfstudio/lib/python3.9/site-packages/torch/_tensor.py", line 431, in __repr__
    return torch._tensor_str._str(self, tensor_contents=tensor_contents)
  File "/User/gunjanchhablani/miniforge3/envs/nerfstudio/lib/python3.9/site-packages/torch/_tensor_str.py", line 664, in _str
    return _str_intern(self, tensor_contents=tensor_contents)
  File "/User/gunjanchhablani/miniforge3/envs/nerfstudio/lib/python3.9/site-packages/torch/_tensor_str.py", line 595, in _str_intern
    tensor_str = _tensor_str(self, indent)
  File "/User/gunjanchhablani/miniforge3/envs/nerfstudio/lib/python3.9/site-packages/torch/_tensor_str.py", line 347, in _tensor_str
    formatter = _Formatter(get_summarized_data(self) if summarize else self)
  File "/User/gunjanchhablani/miniforge3/envs/nerfstudio/lib/python3.9/site-packages/torch/_tensor_str.py", line 133, in __init__
    value_str = f"{value}"
  File "/User/gunjanchhablani//miniforge3/envs/nerfstudio/lib/python3.9/site-packages/torch/_tensor.py", line 933, in __format__
    return self.item().__format__(format_spec)
RuntimeError: CUDA error: an illegal memory access was encountered```

**Comment by maturk** [comment]
@gchhablani if `visible_mask` is "corrputed" it means `self.radii` is corrupted which is what is calculated in the cuda backend. It is strange you are getting this error, I would carefully check your SfM points (maybe visualize them at the first training iteration).

**Comment by gchhablani** [comment]
@maturk 
I am able to visualize things on ns-viewer. The pointcloud looks okay. Can you please share what am I supposed to look for?
Thanks!

**Comment by gchhablani** [comment]
Resolved!

**Comment by gchhablani** [comment]
**What was happening in my case**: 

I was actually manually cropping a pointcloud generate gaussians for particular region. Some of the camera poses inside that region however were pointing outwards (where there were no points because the region was cropped out). So, the problem was that during splatting, the rasterizer was trying to get some gaussians to use for splatting, where there were none present (hence the CUDA error).

**How I solved this**:
By adding some extra "boundary" points from the pointcloud so there is something to look at.
Alternatively, I could have generated random points around my cropped region or removed those camera poses pointing beyond the region.

**Another interesting finding**:
- Setting RGB values to non-ints (by accident) leads to CUDA error too.
